Issue/36 tab accessibility
AdverseApps/Adversarial-Apps-Web pull request #42
Opened 2024-12-26 13:41 UTC by DamiOgboja

# Proposed Changes

* added aria labels and fixed tab navigation for current pages
*

Fixes # .

2025-01-07 06:07 UTC, SavvyDolphin77 commented
Fixes #42

2025-01-07 07:09 UTC, SavvyDolphin77 requested changes
Looks good with the aria tags and the keyboard navigation etc.

Only issue is when testing, if you tab from home to education, you have to press tab again before you can press enter to go to education page and the drop down menu appears. Ideally should transition Home to education where you can click link and menu appears.

The ending where after you tab from submenu, that works without an extra tab press, but for some reason Home to education have to press tab again to work

2025-01-07 16:35 UTC, mechamancy commented
> Looks good with the aria tags and the keyboard navigation etc.
> 
> Only issue is when testing, if you tab from home to education, you have to press tab again before you can press enter to go to education page and the drop down menu appears. Ideally should transition Home to education where you can click link and menu appears.
> 
> The ending where after you tab from submenu, that works without an extra tab press, but for some reason Home to education have to press tab again to work

I wouldn't know how to change it off the top of my head, but the source of the problem seems to be line 84 in navbar.tsx, which counts the text in the Education element as a second element, resulting in the necessary second tab. Home and Search boxes are their own Flex items and do not count the text within. It's not a big problem, but if something can be done with that line, that might be the way to fix it; could get Christian's input as he did the original navbar work

2025-01-14 05:26 UTC, SavvyDolphin77 requested changes
Looks good, though I noticed that there is a long delay after I tab through the submenu before it closes when move onto search. I think this is because it closes menu when off of the Search page onto the search bar which for an accessible user is fine.

Also, when I go backwards and shift tab back through from the search bar back to home, it skips opening the submenu and goes Education then Home. It still opens the submenu though when going backwards. If anything would rather not open submenu when going backwards or if possible have it go backwards through sub menu.

Maybe suggest making an issue for this to work on later though as that is more of a polishing thing and for the most part this is 87% good.

2025-01-15 22:05 UTC, merged