Issue/45 unit testing
AdverseApps/Adversarial-Apps-Web pull request #46
Opened 2024-12-29 22:19 UTC by JimtheBurger

# Proposed Changes

* Adds a Testing Directory
* Has some base tests that tests base functionality of the app

Fixes #45 .

2025-01-07 06:05 UTC, SavvyDolphin77 requested changes
Had a question and a suggestion to be looked at before approving.

2025-01-07 06:05 UTC, SavvyDolphin77 commented on .github/workflows/code_lint_check.yml
> +on: [push]
what was the reason for this change?

2025-01-07 06:05 UTC, SavvyDolphin77 commented on adversarial_apps/src/tests/components/searchbar.test.tsx
> +          { 'Company Name': 'CompanyA', CIK: '0001111111' },
would also recommend testing an actual company as well.

2025-01-07 14:48 UTC, JimtheBurger commented
Check out nock and React Query.

2025-01-07 14:48 UTC, JimtheBurger commented
https://tanstack.com/query/v5/docs/framework/react/overview

2025-01-07 15:25 UTC, JimtheBurger commented on .github/workflows/code_lint_check.yml
> +on: [push]
Because whenever we commit on a Pull Request we will have twice the Github Actions when we only need one. We should either have the linting and testing run on each pull request change or on each commit, not both since they overlap.
![image](https://github.com/user-attachments/assets/4fabb092-3f04-42aa-b01f-6a528079e860)

2025-01-07 15:27 UTC, JimtheBurger commented on adversarial_apps/src/tests/components/searchbar.test.tsx
> +          { 'Company Name': 'CompanyA', CIK: '0001111111' },
Yeah that was one of the tests I was thinking about making before I had to stop over break.

2025-01-07 15:28 UTC, JimtheBurger commented on .github/workflows/code_lint_check.yml
> +on: [push]
I wonder if "push" triggers a GitHub action for when we merge to development? If not we should add that too since a merge could effect linting or testing.

2025-01-07 20:29 UTC, SavvyDolphin77 commented on .github/workflows/code_lint_check.yml
> +on: [push]
makes sense, if push does it on each commit once its in a pull request then I think that makes more sense as you want to test it before its ready to review once you are done since its just linting. Other test cases probably not

2025-01-15 01:44 UTC, SavvyDolphin77 approved these changes
looks good

2025-01-15 01:59 UTC, merged